kind: pipeline
type: docker
name: build-and-push-from-ci

steps:
  - name: build_and_push_to_dockerhub
    image: plugins/docker
    settings:
      # Credentials from Drone Secrets
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # Docker Hub repository name
      repo: mohamedelgarhy/spring-petclinic
      # Tags for the image
      tags:
        - latest
        - "${DRONE_COMMIT_SHA:0:8}"  # Short commit SHA
        - "${DRONE_BUILD_NUMBER}"     # Build number
      # Dockerfile location
      dockerfile: Dockerfile
      # Build arguments
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      # Optional: Add cache optimization
      cache_from:
        - mohamedelgarhy/spring-petclinic:latest

trigger:
  branch:
    - main
  event:
    - push
    - tag
